### ISSUE TITLE
EPIC: Add unit tests for all rules

### ISSUE THREAD

**Issue by liamg** [aquasecurity/defsec#106]
Historically we have tested adaptation and rules end-to-end in the tfsec repository. Now that the rule logic has been broken out, we need more granular tests to ensure the rule logic works in isolation from the adaptation.

You can see how this has been done for [Google BigQuery](https://github.com/aquasecurity/defsec/blob/master/rules/google/bigquery/no_public_access_test.go) as an example.

The templates exists for all tests, we just need to fill in the details and remove the `t.SkipNow()` call for each.

Please raise an issue per service below and assign it to yourself.

### Services
- [x] aws / apigateway #154 
- [x] aws / athena #142 
- [x] aws / autoscaling #170 
- [x] aws / cloudfront #166 
- [x] aws / cloudtrail #144 
- [x] aws / cloudwatch #132 
- [x] aws / codebuild #134 
- [x] aws / config #136 
- [x] aws / documentdb #172 
- [x] aws / dynamodb #177 
- [x] aws / ebs #164 
- [x] aws / ec2 #117 
- [x] aws / ecr #179 
- [x] aws / ecs #181 
- [x] aws / efs #120 
- [x] aws / eks #122 
- [x] aws / elasticache #160 
- [x] aws / elasticsearch #162 
- [x] aws / elb #184 
- [x] aws / iam #187 
- [x] aws / kinesis #126 
- [x] aws / kms #124 
- [x] aws / lambda #156 
- [x] aws / mq #140 
- [x] aws / msk #152 
- [x] aws / neptune #158 
- [x] aws / rds #168 
- [x] aws / redshift #150 
- [x] aws / s3 #190 
- [x] aws / sam #193 
- [x] aws / sns #138 
- [x] aws / sqs #148 
- [x] aws / ssm #128 
- [x] aws / vpc #146 
- [x] aws / workspaces #130 
- [x] azure / appservice #205 
- [x] azure / authorization #207 
- [x] azure / compute #194 
- [x] azure / container #209 
- [x] azure / database #213 
- [x] azure / datafactory #196 
- [x] azure / datalake #198 
- [x] azure / keyvault #215 
- [x] azure / monitor #217 
- [x] azure / network #219 
- [x] azure / securitycenter #211 
- [x] azure / storage #226 
- [x] azure / synapse #200 
- [x] cloudstack / compute #228 
- [x] digitalocean / compute #249 
- [x] digitalocean / spaces #247 
- [x] github / actions #235 
- [x] github / repositories #237 
- [x] google / bigquery #107 
- [x] google / compute #260 
- [x] google / dns #230 
- [x] google / gke #262 
- [x] google / iam #264 
- [x] google / kms #232 
- [x] google / sql #266 
- [x] google / storage #239 
- [x] kubernetes / network #241 
- [x] openstack / compute #243 
- [x] oracle / compute #245

**Comment by vanesasejdiu** [comment]
No rule to test on `general/secrets`
