### ISSUE TITLE
bug: rego_type_error: undefined function result.new

### ISSUE THREAD

**Issue by iod3780** [aquasecurity/defsec#1118]
**Describe the bug**

**To Reproduce**
1. Go to 'https://github.com/aquasecurity/defsec/tree/master/internal/rules/policies/kubernetes#quick-start'
2. Failed to download the main library. URL is invalid. defsec.rego not found.
3. Run the conftest command. I got "rego_type_error: undefined function result.new". 1_host_ipc.rego does not containe "import data.lib.result".

**Comment by simar7** [comment]
Please reopen if issue still exists.
