### ISSUE TITLE
Rules related to sensitive content in configMaps have documentation broken and produce false positives

### ISSUE THREAD

**Issue by rvillane** [aquasecurity/defsec#1133]
Hello, rules avd-ksv-0109 and avd-ksv-0110 recently introduced have a couple of issues:

1) Documentation links included in the output are broken and I did not success going to the aquasec vulnerability database directly to find the rule details
https://avd.aquasec.com/misconfig/avd-ksv-0110
https://avd.aquasec.com/misconfig/avd-ksv-0109

2) Seems like those two rules are implemented using partial matching of keywords such as "KEY", "TOKEN" or "EMAIL" in the configMap key names, but that generates false positives since no actual emails or APIKeys or any other sensitive data is stored, in our case, most matches is either URL's to an email-related service or the name of key in some other system but not the actual key value

Examples:

HIGH: ConfigMap 'dev01-config' in 'dev01' namespace stores sensitive contents in key(s) or value(s) '{"PROJECT_KEY",  "EMAIL_VALIDATION_SERVICE_BASE_URL", "SECRET_KEY_ID"}'
Storing sensitive content such as usernames and email addresses in configMaps is unsafe

HIGH: ConfigMap 'dev01-config' in 'dev01' namespace stores secrets in key(s) or value(s) '{"SECRET_CREDENTIALS_KEY", "SECRET_REDIS_CA_CERTIFICATE_KEY", "JWT_GCP_TOKEN_URL"}'
Storing secrets in configMaps is unsafe

This type of implementation is giving us 2 options:

a) rename the secret keys to less meaning names
b) ignore the 2 rules since they produce false positives

**Comment by rvillane** [comment]
Hello, just checking if any additional information was needed.  Thanks

**Comment by simar7** [comment]
hi @rvillane - thanks for reporting this. I feel this is working as intended. Are you saying that the detected keys/values are being classified as secrets but they aren't? 

If so can you share the part of the configMap with us so we can look into it?

**Comment by rvillane** [comment]
Hi @simar7 , exactly, in our case, we have a k8s ConfigMap that only stores key names that corresponds to entries on a separate Secret Manager service that stores the actual sensitive data, the configMap is only used to keep the specific key names.

Error messages like the following feel a bit misleading, because we do not store any secrets or sensitive data in the config map itself but the current implementation of the rule is just trying to find key words such as: "key", "token" or "email":

- Storing sensitive content such as usernames and email addresses in configMaps is unsafe
- Storing secrets in configMaps is unsafe

Below are some examples of the Key -> Values stored in the config map:

PROJECT_KEY -> project-key-dev
KEY_RING_ID   -> keyring-dev
SECRET_API_CREDENTIALS_KEY -> services-key-dev
REDIS_CA_CERTIFICATE_KEY -> redis-server-ca-key-dev

Can you please confirm is that is the expected behavior of the rule ?

**Comment by simar7** [comment]
hi again @rvillane - you're right that today the rule only looks at certain keywords to identify it as a secret or otherwise. While it isn't the best and certainly can be improved (ideas & PRs welcome), to design a truly correct secret identifying logic would be hard as we aren't able to tell if "services-key-dev" is an actual secret or not. In your case I understand it isn't but I hope you get the idea.

As you mentioned ignoring them as false positives would be the right way to proceed here. Please reopen if you think otherwise. Thanks.
