### ISSUE TITLE
improvement(policies): make policies easier to navigate

### ISSUE THREAD

**Issue by simar7** [aquasecurity/defsec#1158]
### User Story
**As a**: contributor to the defsec project,
**I would like to**: have a simplified project structure for policies*,
**So that**: it's easier to contribute new ones and navigating existing policies

*: In the context of this improvement, policies, rules and signatures are used interchangeably

### What exists today

1. Rules are scattered in different places through the project. This makes it a little harder for new folks to discover and understand the project structure. For instance:

a) Some rego rules: https://github.com/aquasecurity/defsec/tree/master/internal/rules/policies
b) Golang rules: https://github.com/aquasecurity/defsec/tree/master/internal/rules
c) Some rego rules are places alongside with helper policies: https://github.com/aquasecurity/defsec/tree/master/internal/rules/policies/docker and https://github.com/aquasecurity/defsec/tree/master/internal/rules/policies/kubernetes
d) There's a symlink to policies dir that exists on the top level of the project: https://github.com/aquasecurity/defsec/blob/master/policies

Further more as shown by point a) polices are part of the `internal` directory, something that makes them a little obscure to the outer world. IOW, policies can be reused and aren't necessarily only limited to be part of the internals of the defsec project.

### What is desired

In an ideal world (all signatures are Rego based), the directory structure could look like the following:

```shell
$ defsec > tree .
./rules
├── cloud
│   └── policies
├── docker
│   ├── README.md
│   ├── lib
│   ├── policies
│   └── test
└── kubernetes
    ├── README.md
    ├── lib
    └── policies
```

Where furthermore each of the services could look like the following:
```shell
$ defsec > tree ./rules/cloud/policies
rules/cloud/policies
└── aws
    └── rds
        ├── disable_public_access.rego
        ├── disable_public_access_test.rego
```

### Acceptance Criteria

1. Policies should be easier to discover and navigate.

Signed-off-by: Simar <simar@linux.com>

**Comment by itaysk** [comment]
great! another piece of content we need to consider in this structure is compliance reports

**Comment by itaysk** [comment]
do we need the `policies` level? seems redundant?

**Comment by itaysk** [comment]
after we have a stable hierarchy, we can consider applying in to the package name. This could serve us in the future for in the rego level. For example, to apply an input schema at an aws service level. or to query results for a specific service

**Comment by simar7** [comment]
Closed via https://github.com/aquasecurity/defsec/pull/1161
