### ISSUE TITLE
feat(policy): Add more testing for input selectors

### ISSUE THREAD

**Issue by simar7** [aquasecurity/defsec#1200]
we should define (and test) the following cases:
1. selector is not defined (IMO policy applies to all)
2. selector is empty (IMO policy applies to none)
3. selector is defined without subtype (IMO policy applies to all of type)
4. selector is defined with empty subtype (IMO policy applies to none)
5. selector is conflicting with service field (IMO we should remove service field)
6. subtype is partially defined, for example only kind is defined on k8s check (should apply to matching types)
7. subtype is mixing fields from different types, for example using service on k8s check (should consider just what's relevant)

_Originally posted by @itaysk in https://github.com/aquasecurity/defsec/pull/1174#pullrequestreview-1309918374_

**Comment by simar7** [comment]
Trying to understand what's the difference between the various cases you've mentioned. Here's my understanding:

1. selector is not defined
```rego
# METADATA
# title: "RDS Publicly Accessible"
# custom:
#   input:
package builtin.aws.rds.aws0999

deny[res] {
	res := true
}
```

Case 1 is an incomplete policy, today we need the input selector type to correctly determine the kind of policy it is.


2. selector is empty
```rego
# METADATA
# title: "RDS Publicly Accessible"
# custom:
#   input:
#     selector:
package builtin.aws.rds.aws0999

deny[res] {
	res := true
}
```

Case 2 to me seems behaviourally no different than Case 1.


3. selector is defined without subtype
```rego
# METADATA
# title: "RDS Publicly Accessible"
# custom:
#   input:
#     selector:
#     - type: cloud
package builtin.aws.rds.aws0999

deny[res] {
	res := true
}
```

Case 3: This is implemented.

4. selector is defined with empty subtype
```rego
# METADATA
# title: "RDS Publicly Accessible"
# custom:
#   input:
#     selector:
#     - type: cloud
#        subtypes:

package builtin.aws.rds.aws0999

deny[res] {
	res := true
}
```

Case 4: This is implemented.


5. selector is conflicting with service. 
Case 5 Could you define with a short rego policy example?

Case 6 This is implemented.
Case 7 This is implemented. Only what's relevant is processed.

**Comment by itaysk** [comment]
1 & 2: I thought about making it simplest for users writing custom checks, so that they could start with the simplest metadata with just essential fields (name, id). If it's hard then nevermind.

1 vs 2: I thought that omitting a selector implicitly says "I don't care" vs adding an empty selector which explicitly says "don't match with anything". But having said that there's probably isn't a real use case for the latter so let's ignore it. 

5:
```rego
# METADATA
# title: "conflicting selectors"
#   input:
#     selector:
#     - type: cloud
#     - subtype: ec2
# custom:
#   provider: aws
#   service: rds
```

**Comment by simar7** [comment]
> 5:
> 
> ```rego
> # METADATA
> # title: "conflicting selectors"
> #   input:
> #     selector:
> #     - type: cloud
> #     - subtype: ec2
> # custom:
> #   provider: aws
> #   service: rds
> ```

Assuming this is policy is defined for AWS RDS but the user has defined an input selector for EC2. In this case input selector will override as expected, as it is explicitly defined by the user. 

Long term, once we stabilize selectors, we can look at deprecating provider/service custom metadata types (as they only work for cloud, not for k8s, docker etc.). Selectors work for all defsec types.

**Comment by simar7** [comment]
Closed via https://github.com/aquasecurity/defsec/pull/1174

**Comment by itaysk** [comment]
> once we stabilize selectors, we can look at deprecating provider/service custom metadata types

should we track this in an issue?
