### ISSUE TITLE
bug: tests are failing with latest localstack image hardcoded in go-mock-aws

### ISSUE THREAD

**Issue by haykbaluyan** [aquasecurity/defsec#1255]
**Describe the bug**

Latest localstack image no longer supports `docker-entrypoint-initaws.d` mount point. Looks like it was removed as part of the below commit:

https://github.com/localstack/localstack/commit/29010654a86a307e790f6ebb9754ebbca3601637

So defsec tests are failing with latest localstack image (localstack/localstack:latest) which is hardcoded in [go-mock-aws](https://github.com/aquasecurity/go-mock-aws/blob/master/localstack.go#L125). The same tests succeed with localstack/localstack:1.4

Failing test case - [Test_SQSQueueEncrypted in internal/adapters/cloud/aws/sqs/sqs_test.go](https://github.com/averlon-security/defsec/blob/master/internal/adapters/cloud/aws/sqs/sqs_test.go#L30)

The culprit seem to be that, [initComplete](https://github.com/aquasecurity/go-mock-aws/blob/99847deb62b0d46dd65cc6cc38174bce9b7a5971/localstack.go#L153) method returns false infinitely because it always retrieves the first log message.

Official defsec CI build was not broken yet most likely because it is using cached localstack latest image.

**To Reproduce**

1. Remove localstack/localstack:latest image

docker image rm localstack/localstack:latest

2. Run Test_SQSQueueEncrypted

**Expected behavior**

Test is expected to succeed

**Comment by simar7** [comment]
Closed via https://github.com/aquasecurity/defsec/pull/1245
