### ISSUE TITLE
check: apt-get install --no-install-recommends

### ISSUE THREAD

**Issue by atombrella** [aquasecurity/defsec#1272]
**Provider**

Dockerfile

**Severity**

HIGH

**Short Code**

DS029

**Description**

Don't install unnecessary packages. Apt will install recommended packages by default.

**Link**

#1270 is a PR for this check.

https://ubuntu.com/blog/we-reduced-our-docker-images-by-60-with-no-install-recommends

**Comment by simar7** [comment]
Closed via https://github.com/aquasecurity/defsec/pull/1270
