### ISSUE TITLE
How to implement new rules

### ISSUE THREAD

**Issue by Chiranjeevignaidu** [aquasecurity/defsec#1455]
I have a few doubts:
- How can I scan for different services under ec2 like ingress using rego
- Where can I access the scan data or the AWS data related to ec2.

For a rego looking like this 
```rego
deny[res] {
	policy := input.aws.ec2.policies[_]
	value = json.unmarshal(policy.document.value)
	statements = value.Statement
	# Need to write a logic to check for ingress port availability 
	# Need to understand how the data looks like to implement a check
	res = result.new("EC2 Ingress Port 123456 ", policy.document)
}
```
I am not able to understand how the scan data is getting accessed or the raw data location or the location of the `policy` using which I can implement a check for ingress.

**Comment by nikpivkin** [comment]
Hi @Chiranjeevignaidu ! I answered you here https://github.com/aquasecurity/defsec/discussions/1456.
