### ISSUE TITLE
Consolidated Policy List for the provider

### ISSUE THREAD

**Issue by Lingom-R** [aquasecurity/defsec#1490]
Hi,
I would like to see the list of policies from defsec based on the provider. The following link shows 404; seems the "Rules" directory is not present in GitHub.

[github.com/aquasecurity/defsec/pkg/rules](url)

**Comment by nikpivkin** [comment]
Hi @Lingom-R !

At the moment defsec is being refactored and split into components. All policies can be found in the [trivy-policies](https://github.com/aquasecurity/trivy-policies/tree/main/rules) repository.

**Comment by simar7** [comment]
@Lingom-R you can still see that for every release including the latest one https://github.com/aquasecurity/defsec/tree/v0.93.1/rules

As @nikpivkin mentioned we are refactoring the code to make it more manageable but it is not released just yet. In the meantime please refer to the released versions as above.
