### ISSUE TITLE
Bucket logging not picked up if target bucket contains !Ref keyword

### ISSUE THREAD

**Issue by Phylu** [aquasecurity/defsec#454]
When using `!Ref` in the LoggingConfiguration of an S3 bucket, the `enable-bucket-logging` rule (https://cfsec.dev/docs/s3/enable-bucket-logging/#s3) is displayed erroneously.

I have configured logging for an S3 bucket as follows:

```
      LoggingConfiguration:
          DestinationBucketName: !Ref LogBucket
          LogFilePrefix: access-logs
```

cfsec shows an error, that bucket logging is not enabled. If I remove the reference to the log bucket name as follows, the error is not displayed:

```
      LoggingConfiguration:
          DestinationBucketName: log-bucket
          LogFilePrefix: access-logs
```

**Comment by owenrumney** [comment]
This is fixed in defsec now - as cfsec is no longer maintained, Trivy (https://github.com/aquasecurity/trivy) has been updated with the fix.
