### ISSUE TITLE
False positive: No public access block (AWS S3)

### ISSUE THREAD

**Issue by CptKirk** [aquasecurity/defsec#459]
Hello,

I am currently experiencing false positives when scanning valid Terraform JSON with tfsec.
My JSON contains following resources:
```json
"aws_s3_bucket": {
  "live-s3": {
    "bucket": "test-bucket"
  }
},
"aws_s3_bucket_public_access_block": {
  "s3-bucket-access-block": {
    "block_public_acls": true,
    "block_public_policy": true,
    "bucket": "${aws_s3_bucket.live-s3.id}",
    "ignore_public_acls": true,
    "restrict_public_buckets": true
  }
}
```
Nonthenless I get multiple warnings saying that I do not configure a public access block for my bucket which is clearly not correct.
I already searched for related issues and found this [one](https://github.com/aquasecurity/tfsec/issues/1450).
It is marked as closed but there are still cases where this false positive will emerge. I tried to pinpoint the problem and it seems that the `referencesFromExpression()` function in file `parsers/terraform/attribute.go` misses a case where the expression can be of type `*hcl/v2/json.expression`. I tried to fix this behaviour, but the `expression` type is not exported so the fix has to use reflection.
I propose the following changes for the function:
```go
func (a *Attribute) referencesFromExpression(expression hcl.Expression) []*Reference {
	var refs []*Reference
	noTypeMatch := false
	switch t := expression.(type) {
	case *hclsyntax.ConditionalExpr:
		// no changes
	case *hclsyntax.ScopeTraversalExpr:
		// no changes
	case *hclsyntax.TemplateWrapExpr:
		// no changes
	case *hclsyntax.TemplateExpr:
		// no changes
	case *hclsyntax.TupleConsExpr:
		// no changes
	case *hclsyntax.RelativeTraversalExpr:
		// no changes
	default:
		noTypeMatch = true
	}

	if !noTypeMatch {
		return refs
	}

	// Can not go inside the switch case because the hcl/v2/json.expression type is not exported
	if reflect.TypeOf(expression).String() == "*json.expression" {
		if ref, err := createDotReferenceFromTraversal(a.module, expression.Variables()...); err == nil {
			refs = append(refs, ref)
		}
	}

	return refs
}
```
When I run my test with the new implementation the false positive is not shown anymore. Are those changes viable for a PR? If not, I can do some fixes first and then open a PR.

**Comment by liamg** [comment]
Hi @CptKirk - thanks, this looks like a nice solution. I think you could move the code inside the `default:` case of the type switch (and only set `noTypeMatch` if your `if` fails.).

**Comment by liamg** [comment]
Btw, the code is now in `pkg/terraform/attribute.go`

**Comment by CptKirk** [comment]
@liamg Thanks for your input. I moved the code inside the `default:` case, but setting the `noTypeMatch` var to `true` if the `if` statement fails yields a compile error, because the variable is not used. Therefore I will exclude the `noTypeMatch` var from my PR.
