### ISSUE TITLE
Json formatter does not output passed or ignored checks when specified.

### ISSUE THREAD

**Issue by JoeButler99** [aquasecurity/defsec#587]
https://github.com/aquasecurity/defsec/blob/0d66c2f264b27ea8ee78ee3601ac0fa3bd88dad6/pkg/formatters/json.go#L13

This is surely a bug - it stops the json outputer displaying failed or ignored checks even when the arguments are specified. (I tested with a locally patched version of the package and the json outputs seems to work as expected. (I didnt run any tests)

        for _, result := range results {

**Comment by owenrumney** [comment]
Good spot, thanks @JoeButler99
