### ISSUE TITLE
bug: google-gke-metadata-endpoints-disabled being reported incorrectly

### ISSUE THREAD

**Issue by shpml** [aquasecurity/defsec#647]
**Describe the bug**
The `google-gke-metadata-endpoints-disabled` rule is being reported on`google_container_cluster` even though the setting `disable-legacy-endpoints = true` is set on the node pool with resource `google_container_node_pool`. This is probably only relevant when not using the default node pool with `google_container_cluster`. 

**To Reproduce**
Implement the node pool similar to the code in [example-usage---with-a-separately-managed-node-pool-recommended
](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#example-usage---with-a-separately-managed-node-pool-recommended).

**Expected behavior**
If `remove_default_node_pool = true` is set on `google_container_cluster` then this rule should probably be triggered if the setting isn't applied to `google_container_node_pool`.

**System Info**

 - tfsec version: `v1.18.0`
 - terraform version: `v1.1.7`
 - OS: `Mac OS 12.2.1`

Additionally, the fix documented in https://aquasecurity.github.io/tfsec/v1.18.0/checks/google/gke/metadata-endpoints-disabled/ should be in the `node_config` block.

```
  node_config {
    metadata = {
      disable-legacy-endpoints = true
      }
    }
```

**Comment by mattb18** [comment]
Should this have been closed? The fix does not seem to have worked for me and the documentation has not been updated.

I added the following to each node pool:

`
    metadata = {
      disable-legacy-endpoints = "true"
    }
`

**Comment by boguszj** [comment]
It seems to be expecting a block instead of a map / object:
`metadata = { disable-legacy-endpoints = "true" }` is detected as a violation and
`metadata { disable-legacy-endpoints = "true" }` is not, despite the second one not being correct.

**Comment by mattb18** [comment]
Bump

**Comment by alexsuninsth** [comment]
I might be doing something wrong but my `tfsec` still reports false positive on the below code:

`resource "google_container_node_pool" "gke_cluster_nodes" {
 ...

  node_config {
    ...
    workload_metadata_config {
      mode = "GKE_METADATA"
    }

    metadata = {
      // Explicitly remove GCE legacy metadata API endpoint.
      disable-legacy-endpoints = "true"
    }

    labels = var.labels
  } // endof node_config block
  }`
  
  `tfsec` version is `v1.28.1`

**Comment by ethankent** [comment]
For anyone experiencing the same issue @alexsuninsth describes. Try using the value `true` (bool) rather than `"true"` (string).
