### ISSUE TITLE
bug: PSS rego issues

### ISSUE THREAD

**Issue by joebowbeer** [aquasecurity/defsec#669]
List of issues with [rule/kubernetes/policies/pss](https://github.com/aquasecurity/defsec/tree/master/internal/rules/kubernetes/policies/pss):

baseline vs https://kubernetes.io/docs/concepts/security/pod-security-standards/#baseline

* [x] Missing: rule for `windowsOptions.hostProcess` https://github.com/aquasecurity/defsec/pull/686
* [x] Missing: baseline rule for seccomp profile: seccompProfile.type must not be explicitly set to Unconfined (but may be undefined) https://github.com/aquasecurity/defsec/pull/686

restricted vs https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted

* [x] Bug: #668 volume type csi _should_ be allowed
* [x] Missing: check runAsUser != 0, though there is a _general_ rule that checks runAsUser > 10000 https://github.com/aquasecurity/defsec/pull/688
* [x] Extraneous: pss/restricted contains a rule for runAsGroup that is not specified in doc https://github.com/aquasecurity/defsec/pull/688
* [x] Missing: check for explicit seccompProfile type. The doc says that the absence of a seccomp profile type is prohibited, but the rego rule does not deny it https://github.com/aquasecurity/defsec/pull/688
* [x] Missing: check that containers drop ALL capabilities and only add back the NET_BIND_SERVICE capability if needed; there are two rules outside of pss that check for dropped capabilities, but there is no rule verifying that NET_BIND_SERVICE is the only capability added back https://github.com/aquasecurity/defsec/pull/688

**Comment by liamg** [comment]
Thanks @joebowbeer - I'm looking at sorting this now.
