### ISSUE TITLE
bug: IAM ignore anomalies

### ISSUE THREAD

**Issue by coobachey** [aquasecurity/defsec#675]
**Describe the bug**

We are seeing some different outcomes and exclusion actions within IAM policy docs

**To Reproduce**
Run tfsec against the Tf below 

**Expected behavior**
Is not allow the top statement with * in resource or the action after adding a ignore on the second statement
**Screenshots/Output**

**System Info**

 - tfsec version: `1.19.*   +. `
 - terraform version: `tfenv 0.13.7 `
 - OS: `?`

**Example Code**

```data "aws_iam_policy_document" "export_policy_doc" {
  statement {
    effect  = "Allow"
    actions = [
      "s3:Get*",
      "s3:PutObject"
    ]
    resources = ["*"]
  }

  statement {
    effect = "Allow"
    actions = [
        "ec2:CancelConversionTask",
        "ec2:CancelExportTask",
        "ec2:CreateImage",
        "ec2:CreateInstanceExportTask",
        "ec2:CreateTags",
        "ec2:DescribeConversionTasks",
        "ec2:DescribeExportTasks",
        "ec2:DescribeExportImageTasks",
        "ec2:DescribeImages",
        "ec2:DescribeInstanceStatus",
        "ec2:DescribeInstances",
        "ec2:DescribeSnapshots",
        "ec2:DescribeTags",
        "ec2:ExportImage",
        "ec2:ImportInstance",
        "ec2:ImportVolume",
        "ec2:StartInstances",
        "ec2:StopInstances",
        "ec2:TerminateInstances",
        "ec2:ImportImage",
        "ec2:ImportSnapshot",
        "ec2:DescribeImportImageTasks",
        "ec2:DescribeImportSnapshotTasks",
        "ec2:CancelImportTask"
    ]
    resources = ["*"] #tfsec:ignore:aws-iam-no-policy-wildcards:exp:2022-11-27
  }
}

resource "aws_iam_policy" "export_policy" {
  name        = "export_policy"
  description = "Import/Export"
  path        = "/"
  policy      = data.aws_iam_policy_document.export_policy_doc.json
}
```
**Additional context**

we have found interesting, & explorative outcomes, moving ignore statement, to a action item line, vs resource, and of course above the top level TF resource block. 

Example action line: 
 ```    effect  = "Allow"
    actions = [ "ecr:GetAuthorizationToken", #tfsec:ignore:aws-iam-no-policy-wildcards
        "ecr:GetAuthorizationToken",
        "ecr:BatchCheckLayerAvailability",
        "ecr:GetDownloadUrlForLayer",
        ```
        
        
        I would like to help contribute to Documentation after gathering some more "How it Works" for the ignores in IAM. 
        Please and Thank you

**Comment by liamg** [comment]
Your example seems to work in the latest defsec (the top `*` is detected but the one with the ignore one is not). I'll pull latest defsec into tfsec soon as it seems this was fixed elsewhere. Let us know if the next version of tfsec doesn't work!
