### ISSUE TITLE
bug: module loading from .terraform directory is still broken

### ISSUE THREAD

**Issue by sergei-ivanov** [aquasecurity/defsec#708]
There were some changes in #648 that addressed infinite loop issue in tfsec (see https://github.com/aquasecurity/tfsec/issues/1594).
Unfortunately that change has introduced another regression / bug in the resolution of modules from `.terraform` directory.

Example. The source code in our `downstream_repo` imports module from `upstream_repo` like this:
```hcl
module "label" {
  source = "github.com/org/upstream_repo.git//aws/modules/label?ref=v4.6.2"

  # ... <module parameters>
}

```

When I run tfsec, it hangs for a few minutes, not using any CPU, just blocked.

The log from `tfsec --verbose`:
```
25:37.950125581 terraform.parser.<root>.evaluator Starting submodule evaluation...
25:37.951152611 terraform.parser.<root>.evaluator Module 'module.label' resolved to path 'home/sergey/projects/org/downstream_repo/terraform/ci2/deploy/modules/squid/.terraform/modules/label/aws/modules/label/aws/modules/label?ref=v4.6.2' in filesystem '&{/ /}' using modules.json
25:37.951164983 terraform.parser.<root>.evaluator locating non-initialised module 'github.com/org/upstream_repo.git//aws/modules/label?ref=v4.6.2'...
25:37.951170009 terraform.parser.<root>.evaluator.resolver Resolving module 'module.label' with source: 'github.com/org/upstream_repo.git//aws/modules/label?ref=v4.6.2'...
25:37.951173360 terraform.parser.<root>.evaluator.resolver Cache is disabled.
25:37.951180247 terraform.parser.<root>.evaluator Failed to load module 'failed to resolve module 'module.label' with source: github.com/org/upstream_repo.git//aws/modules/label?ref=v4.6.2'. Maybe try 'terraform init'?
```

As a matter of fact, the `.terraform/modules/config.json` looks like this:
```json
{
  "Modules": [
    {
      "Key": "label",
      "Source": "github.com/AdaptiveConsulting/infrastructure.git//aws/modules/label?ref=v4.6.2",
      "Dir": ".terraform/modules/label/aws/modules/label"
    },
    # ... <other modules>
  ]
}
``` 

`Dir` points to a correct relative path inside the root module directory.

The problematic block of code appears to be this:
https://github.com/aquasecurity/defsec/blob/c2fe370ed9f86cafcea109782a6521027d6de1e5/pkg/scanners/terraform/parser/load_module.go#L127-L129

For some reason it parses the module source and appends everything after the `//` to the path, which results in an invalid path.

System information:
```
$ terraform version
Terraform v1.0.11

$ tfsec --version
v1.26.0

$ uname -irs
Linux 5.4.0-120-generic x86_64

$ lsb_release -d
Description:	Ubuntu 20.04.4 LTS
```

**Comment by liamg** [comment]
I think this may be the `modules.json` format being written by the older terraform version. I don't seem to have this issue with v1.2.6 of terraform using the tfsec version you specified. Could you try updating terraform or removing the `.terraform` directory?

**Comment by sergei-ivanov** [comment]
At the moment we are still using Terraform 1.0.x (see issue description). There are plans to upgrade Terraform, but not in the near term (due to the size of the codebase and number of projects/states that need to be upgraded and tested). 

Will it be possible to make tfsec compatible with at least Terraform 1.0.x and 1.1.x? I guess there is a large enough number of other teams out there, who are not yet running the latest Terraform, so I don't think that the request is unreasonable.

Otherwise it should be clearly stated that tfsec is only being tested with the latest version of Terraform, and compatibility with earlier versions is not guaranteed. Such constraint is also not unreasonable (e.g., because of limited development resources), but just needs to be explicitly stated.

**Comment by liamg** [comment]
Yeah, that's totally reasonable :+1: 

It may not be the issue, I'll look into it further this afternoon.
