### ISSUE TITLE
Map ignored results as "skipped" in JUnit

### ISSUE THREAD

**Issue by askingcat** [aquasecurity/defsec#719]
Currently any [ignored](https://github.com/aquasecurity/defsec/blob/872e1c2668813a9a0730c80ae6266fe2ed37db73/pkg/scan/result.go#L19) scan result will be mapped as a [failure](https://github.com/aquasecurity/defsec/blob/872e1c2668813a9a0730c80ae6266fe2ed37db73/pkg/formatters/junit.go#L96-L121) for JUnit. 

This might be a bit confusing and can make it more difficult to integrate other tools. 

While it would not be a perfect fit, I wonder whether it would make more sense to map "ignored" as "skipped" for JUnit. If you are OK with such a change, I would be happy to try to create a PR for this :-).

**Comment by owenrumney** [comment]
Hey @askingcat  - still willing to PR this? I'm happy with the proposed solution :+1:

**Comment by askingcat** [comment]
Hey @owenrumney,

sure :smile:.

**Comment by askingcat** [comment]
The merged code is already included in [tfsec 1.27.2](https://github.com/aquasecurity/tfsec/releases/tag/v1.27.2) and I just confirmed that it works :slightly_smiling_face:.
