### ISSUE TITLE
bug: Terraform parser: options are not applied to ModuleParser

### ISSUE THREAD

**Issue by PaulMart1** [aquasecurity/defsec#722]
**Describe the bug**
When adding options to the terraform parser, those are not applied to child parsers when calling newModuleParser

**To Reproduce**
This example may not be valid terraform but it is a stripped version of my code which will show the error
1. Modify the main command defsec to 
  - import `github.com/aquasecurity/defsec/pkg/scanners/terraform`
  - add the option `terraform.ScannerWithDownloadsAllowed(false)` 
2. Create a directory with the following files:
`main.tf`: 
```
module "test" {
  source = "./other_dir"
}
```

`other_dir/main.tf`
```
module "test-module" {
  source = "github.com/fake/address"
}
```

3. Scan the directory (`go run cmd/defsecf/main.go /path/to/example_dir`)
4. See error : The shell will prompt for a GitHub username

**Expected behavior**
If external modules are not found locally, it should not try to download those when the DownloadsAllowed flag is disabled

**System Info**
 - OS: ubuntu 20.04
 - Go: 1.18.3 linux/amd64
 - defsec: master branch ([5f54145](https://github.com/aquasecurity/defsec/commit/5f54145b0d84511d90d381920f5017e237c08b46))

**Example Code**
See above

**Additional context**
From what I can see, In the terraform parser, options of a parent parser are not transmitted to the new parser [when created](https://github.com/aquasecurity/defsec/blob/master/pkg/scanners/terraform/parser/parser.go#L121) 

I have two ideas of modifications:
- in line 115, add the parser options to the constructor but this was changed in [this commit](https://github.com/aquasecurity/defsec/commit/c2fe370ed9f86cafcea109782a6521027d6de1e5)
- in line 122, change so that option is applied to the moule parser instead of the parent parser (options will not be transmitted to the ModuleParser childs, but can it happen ?)

**Comment by liamg** [comment]
Good spot, thank you :)
