### ISSUE TITLE
Adjust s3 logging checks for New S3 TF block

### ISSUE THREAD

**Issue by coobachey** [aquasecurity/defsec#733]
When adoptin the better broken out items for an S3 bucket we need to change how the defsec rule checks:

https://github.com/aquasecurity/defsec/blob/master/avd_docs/aws/s3/AVD-AWS-0089/Terraform.md

Does not handle the new option of the `aws_s3_bucket_logging` resource.

example of results with current

```
Result #1 MEDIUM Bucket does not have logging enabled 
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  main.tf:51-55
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   51    resource "aws_s3_bucket_logging" "s3-ingest" {
   52      bucket        = aws_s3_bucket.s3-ingest.id
   53      target        = data.aws_s3_bucket.s3_logging_bucket.id
   54      target_prefix = "s3/${aws_s3_bucket.s3-ingest.id}/"
   55    }
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
          ID aws-s3-enable-bucket-logging
      Impact There is no way to determine the access to this bucket
  Resolution Add a logging block to the resource to enable access logging
```

**Comment by owenrumney** [comment]
Hey @coobachey  - have you got a small example of this not working? Updates to support the new v4 provider have been in for a while 

https://github.com/aquasecurity/defsec/blob/master/internal/adapters/terraform/aws/s3/bucket.go#L112-L129

**Comment by coobachey** [comment]
Hi Owen,   Yes see below the code , that I fail to get the Rule not to catch `aws-s3-enable-bucket-logging`


TF : 

`data "aws_s3_bucket" "s3_logging_bucket" {
    bucket = "bucket.test.com"
  
}

# resource "aws_s3_bucket" "s3_logging_bucket" {
#   bucket = "my-tf-log-bucket"
# }

resource "aws_s3_bucket" "s3-ingest" {
bucket = "ingest"
}

resource "aws_s3_bucket_acl" "ingest_acl" {
  bucket = aws_s3_bucket.s3-ingest.id
  acl    = "private"
}

resource "aws_s3_bucket_public_access_block" "example" {
  bucket = aws_s3_bucket.s3-ingest.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_logging" "s3-ingest-log" {
      bucket        = aws_s3_bucket.s3-ingest.id
      target        = aws_s3_bucket.s3_logging_bucket.id
      target_prefix = "s3/${aws_s3_bucket.s3-ingest.id}/"
}

resource "aws_s3_bucket_versioning" "versioning_example" {
  bucket = aws_s3_bucket.s3-ingest.id
  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "example" {
  bucket = aws_s3_bucket.s3-ingest.bucket

  rule {
    apply_server_side_encryption_by_default {
      kms_master_key_id = aws_kms_key.mykey.arn
      sse_algorithm     = "aws:kms"
    }
  }
}`

**Comment by owenrumney** [comment]
I think you may have an error in your terraform - the logging block should be `target_bucket` not `target` https://registry.terraform.io/providers/hashicorp/aws%20%20/latest/docs/resources/s3_bucket_logging#target_bucket

With that change, it works

**Comment by coobachey** [comment]
Thank you!  simple fix but escaped me! closing
