### ISSUE TITLE
bug: azure-container-use-rbac-permissions misreporting for clusters without Azure RBAC

### ISSUE THREAD

**Issue by MorpheusXAUT** [aquasecurity/defsec#778]
**Describe the bug**
The `azure-container-use-rbac-permissions` rule was adapted a few weeks back in #685 to support the new `azure_active_directory_role_based_access_control` block for the `azurerm_kubernetes_cluster` resource. Whilst the old `role_based_access_control_enabled` (actually enabling RBAC in the k8s cluster) is still supported/being checked, the rule misreports if `role_based_access_control_enabled` is used together with `azure_active_directory_role_based_access_control`, but the new block doesn't have `azure_rbac_enabled` set.

Azure offers two features to supplement RBAC:

1. [Azure Active Directory integration](https://docs.microsoft.com/en-us/azure/aks/concepts-identity#azure-ad-integration), allowing for AAD to be used for _authentication_ via an OpenID Connect identity provider. The current recommended way is using an [AKS-managed Active Directory integration](https://docs.microsoft.com/en-us/azure/aks/managed-aad), enabled using the [`managed`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#managed) flag in the [`azure_active_directory_role_based_access_control`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#azure_active_directory_role_based_access_control) block.
2. [Azure RBAC for Kubernetes Authorization](https://docs.microsoft.com/en-us/azure/aks/manage-azure-rbac), allowing for Azure's RBAC/IAM functionality to be used for _authorizing_ k8s calls as well. This feature is enabled using the [`azure_rbac_enabled`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#azure_rbac_enabled) flag in the [`azure_active_directory_role_based_access_control`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#azure_active_directory_role_based_access_control) block.

At the moment, Azure AKS seems to support three ways of running RBAC for a k8s cluster:

1. `role_based_access_control_enabled = true`, no `azure_active_directory_role_based_access_control` block at all: RBAC in k8s is enabled, but no integration into either Azure Active Directory (AAD) or Azure RBAC exist. All identities are managed by k8s, all authorization checks are performed by k8s.
2. `role_based_access_control_enabled = true`, `azure_active_directory_role_based_access_control.managed = true`: RBAC in k8s is enabled, AAD integration is enabled. Identities are provided by k8s as well as Active Directory, all authorization checks are performed by k8s.
3. `role_based_access_control_enabled = true`, `azure_active_directory_role_based_access_control.azure_rbac_enabled = true`: RBAC in k8s and Azure are enabled, AAD integration is enabled. Identities are provided by k8s as well as Active Directory, AAD principals are authorized using Azure RBAC, k8s principals are authorized using k8s.

At the moment, `tfsec` / the `azure-container-use-rbac-permissions` rule will work correctly for cases 1 and 3, however will misreport for case 2, claiming RBAC is not enabled.
A quote from the documentation about [Azure RBAC for k8s authorization](https://docs.microsoft.com/en-us/azure/aks/manage-azure-rbac#before-you-begin): `When enabled, Azure AD principals will be validated exclusively by Azure RBAC while regular Kubernetes users and service accounts are exclusively validated by Kubernetes RBAC`. I believe that case 2 should still be considered as "valid" since it uses RBAC, albeit "just" the k8s one, however users might prefer having all their RBAC checks in one place without having to rely on Azure RBAC or disabling an otherwise important `tfsec` rule for their cluster.

**To Reproduce**
1. Define an Azure AKS cluster with (k8s) RBAC and managed AAD integration enabled, but Azure RBAC disabled:
```
resource "azurerm_kubernetes_cluster" "misreporting_example" {
    role_based_access_control_enabled = true # Enable k8s RBAC
    azure_active_directory_role_based_access_control {
      managed = true # Enable AKS-managed Azure AAD integration 
      azure_rbac_enabled = false # Explicitly disable Azure RBAC for Kubernetes Authorization
    }
 }
```
2. Run `tfsec` with the rule `azure-container-use-rbac-permissions` enabled
3. See error: ![error](https://i.imgur.com/yjBPrMm.png)

**Expected behavior**
I would expect the `azure-container-use-rbac-permissions` rule to validate successfully if `role_based_access_control_enabled` is enabled, even if `azure_rbac_enabled` is disabled.

**Output of your tfsec command with --debug flag**
_No relevant output_

**System Info**
 - tfsec version: `v1.26.3`
 - terraform version: `v0.13.5`
 - azurerm version: `v3.16.0`
 - OS: `Ubuntu 22.04 LTS`
 
**Example Code**
_see above_

**Additional context**
I believe this could be supported relatively easily by changing [this line](https://github.com/aquasecurity/defsec/blob/master/internal/adapters/terraform/azure/container/adapt.go#L98) to check the `cluster.RoleBasedAccessControl.Enabled` [set above](https://github.com/aquasecurity/defsec/blob/master/internal/adapters/terraform/azure/container/adapt.go#L90) before overriding it with the value of `azure_rbac_enabled`. Not quite sure if we'd need to adapt the metadata as well.
Happy to supply a tiny PR if you'd like.

**Comment by liamg** [comment]
Thanks for the great detail on this issue, fix incoming!
