### ISSUE TITLE
bug: Iam * no policy wildcard - rds Cluster-snapshot backup 

### ISSUE THREAD

**Issue by coobachey** [aquasecurity/defsec#906]
**Describe the bug**
We found that no-policy-wildcard is tripping on a well formatted IAM block. It may be not handled in the code here: [IAM-Func](https://github.com/aquasecurity/defsec/blob/586c995b07ebff99a48b46177daaf576b26210af/internal/rules/aws/iam/no_policy_wildcards.go#L92)

**To Reproduce**
Using iam statement 
```
statement {
    actions = [
      "rds:DeleteDBClusterSnapshot",
      "rds:ModifyDBClusterSnapshotAttribute"
    ]
    effect    = "Allow"
    resources = ["arn:aws:rds::${account_id}:cluster-snapshot:awsbackup:*"]
```

no-policy-wildcard  is reported no matter what we change. Keeping in mind that auto generated label is created.

**Expected behavior**
If the specific actions labeled and concise, should pass

**Output of your tfsec command with --debug flag**

**System Info**

 - tfsec version: `latest`
 - terraform version: `latest`
 - OS: `NA`

It smells like we might need to add logic like s3. but maybe there is a smarter way (no copy pasta)
```if strings.HasSuffix(resource, "/*") && strings.HasPrefix(resource, "arn:aws:s3") ```

**Comment by amascia** [comment]
Hi,
To add to this issue, starting from defsec v0.74.0, the IAM `no_policy_wildcards` vulnerability is not detected anymore when running defsec on the `no_policy_wildcards.tf.go` file.

It seems like it is because of the addition of the `CIS_AWS_1_4` framework in [this commit](https://github.com/aquasecurity/defsec/commit/fdcb2e0e1060f5e67d65ae7252d7c2fc6ad19510#diff-f1ba05aeb550229b6885527b1f6488514e09c5c1f6a143c380ef0756044acf35).

**Comment by liamg** [comment]
Hi @coobachey - I think it's likely tripping because of the wildcard at the end of the resource identifier? Does it still report when you use specific resource names?

@amascia Thanks, this will be fixed today.

**Comment by coobachey** [comment]
You are correct  it is seeing the *  at end for one part.
It does trip when we use specific resource,  we placed a "somestring\*"  at the end.  I think its due to the check requiring Pre string "arn:aws:s3" and end of "/*"
At least I am perceive it that way.  So on this particular Database backups, the arn string is built differently, further we cannot know what appended string will start with as there is auto generated data when snapshot is created (aws automation). 
arn:aws:rds.  ...   :*
"arn:aws:rds::${account_id}:cluster-snapshot:awsbackup:*" 

Have to run but i'll try and get back around this week for more details

**Comment by owenrumney** [comment]
Closing as this appears to be resolved. Please reopen if required
